version: "3.4"
services:
  mysql:
    build: rdb/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=market
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=BambooTuna
      - MYSQL_PASSWORD=pass
  redis:
    image: redis:3.2.4-alpine
    restart: always
    ports:
      - 6379:6379
  boot:
#    image: bambootuna/marketserver:latest
    build: ./boot/target/docker/stage
    restart: always
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST_SESSION=redis
      - REDIS_HOST_OAUTH2=redis
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=market
      - ALLOWED_ORIGIN=http://localhost:9050
      - LINE_CLIENT_ID=123465789
      - LINE_CLIENT_SECRET=123465789
      - LINE_REDIRECT_URI=http://localhost:9050/oauth2/signin/line

    depends_on:
      - mysql
      - redis
